Added nVidia driver package install.

diff --git a/install-files/bumblebee-uninstall b/install-files/bumblebee-uninstall
--- a/install-files/bumblebee-uninstall
+++ b/install-files/bumblebee-uninstall
@@ -52,7 +52,7 @@ if [ "$UID" != "$ROOT_UID" ] ; then
     exit 1
 fi
 
-if [ "$HOME" == "/root" ] ; then
+if [ "$HOME" == "/root" ] && [ "$DISTRO" != OPENSUSE ] ; then
     echo "Do not run this script as the root user"
     echo
     echo "Please run the script with: sudo bumblebee-uninstall"
@@ -68,7 +68,15 @@ echo
 echo "This script will remove bumblebee completely"
 echo "and also clean up after earlier versions"
 echo
-if [ $DISTRO = FEDORA ] && [ "$ARCH" = "x86_64" ]; then
+if [ "$DISTRO" == OPENSUSE ] ; then
+
+    if [ `ps -ea | grep X | wc -l` -gt 0 ] ; then
+      echo "X server is still active. Please go to runlevel 3 and try again."
+      echo "( Login as root and run \"init 3\". Use \"init 5\" to activate the X server again )"
+      exit 1
+    fi
+fi
+if [ $DISTRO = FEDORA ] && [ "$ARCH" = "x86_64" ] ; then
     echo "Uninstalling will most likely kill your X-session"
     echo "please make sure that all your data is saved"
     echo
@@ -94,8 +102,14 @@ sleep 5
 echo 
 if [ $DISTRO = UBUNTU  ] || [ $DISTRO = DEBIAN  ]; then
 
-    #Kill the nvidia X server
+    #	Kill the nvidia X server
     /etc/init.d/bumblebee disable
+
+    #	Make sure the card is enabled
+    if [ -x /usr/local/bin/bumblebee-enablecard ]; then
+      /usr/local/bin/bumblebee-enablecard
+    fi
+
     echo "Removing nVidia driver package"
     echo
     apt-get -y --purge remove nvidia-current
@@ -107,25 +121,71 @@ if [ $DISTRO = UBUNTU  ] || [ $DISTRO = DEBIAN  ]; then
 
 elif [ $DISTRO = OPENSUSE ]; then
 
-    #Kill the nvidia X server
+    #	Kill the nvidia X server
     /etc/init.d/bumblebee disable
     chkconfig bumblebee off 
     echo "Removing VirtualGL package"
     echo
-    zypper remove VirtualGL
+    zypper --no-refresh --non-interactive remove VirtualGL
+
+    #	Make sure the card is enabled
+    if [ -x /usr/local/bin/bumblebee-enablecard ]; then
+      /usr/local/bin/bumblebee-enablecard
+    fi
 
     FOUND=`rpm -qa|grep x11-video-nvidia`
-    if [ "$FOUND" != "" ] || [ -d /usr/X11R6/lib-nvidia ]  ; then
+    if [ "$FOUND" != "" ] || ( [ -d /usr/X11R6/lib-nvidia ] && [ ! -d /usr/X11R6/nvidia ] ) ; then
 	if [ -f /usr/local/bin/bumblebee-check ] ; then
+	  #
+	  #	Cleanup 3D hack for the repository
+	  #
 	  /usr/local/bin/bumblebee-check -restore
 	fi
+    fi
+
+    if [ -f /usr/bin/nvidia-uninstall ] ; then
+
+	echo "Uninstalling nVidia package"
+
+	#
+	#	Cleanup 3D hack for the nVidia package part 1
+	#
+	if [ "$ARCH" == "i686" ] ; then
+	  rm -f /usr/lib/libGL.so.*
+	  mv -f /usr/X11R6/nvidia/lib/libnvidia-wfb.* /usr/X11R6/nvidia/lib/xorg/modules
+	  pushd /usr/X11R6/nvidia/lib/xorg/modules > /dev/null
+	  ln -sf libnvidia-wfb.so.1 libwfb.so
+	  popd > /dev/null
+	else
+	  rm -f /usr/lib/libGL.so.*
+	  rm -f /usr/lib64/libGL.so.*
+	  mv -f /usr/X11R6/nvidia/lib64/libnvidia-wfb.* /usr/X11R6/nvidia/lib64/xorg/modules 
+	  pushd /usr/X11R6/nvidia/lib64/xorg/modules > /dev/null
+	  ln -sf libnvidia-wfb.so.1 libwfb.so
+	  popd > /dev/null
+	fi
+
+	#
+	#	Uninstall nVidia package
+	#
+	/usr/bin/nvidia-uninstall -s
+
+	#
+	#	Cleanup 3D hack for the nVidia package part 2
+	#
+	rm -rf /usr/X11R6/lib-nvidia
+	rm -rf /usr/X11R6/lib64-nvidia
+	rm -rf /usr/lib/xorg-nvidia
+	rm -rf /usr/lib64/xorg-nvidia
+
+	rm -rf /usr/X11R6/nvidia
     fi
 
     rm /etc/pm/power.d/bumblebee-disablecard-on-powerup
 
 elif [ $DISTRO = FEDORA ]; then
 
-    #Stop the nvidia X server
+    #	Stop the nvidia X server
     service bumblebee stop
     chkconfig bumblebee off 
 
@@ -136,6 +196,11 @@ elif [ $DISTRO = FEDORA ]; then
         rm /etc/profile.d/virtualgl.sh
     fi
 
+    #	Make sure the card is enabled
+    if [ -x /usr/local/bin/bumblebee-enablecard ]; then
+      /usr/local/bin/bumblebee-enablecard
+    fi
+
     # New method for x86_64 but still the old one for i686
     if [ "$ARCH" = "x86_64" ]; then
         echo "Removing nVidia driver package"
@@ -143,12 +208,6 @@ elif [ $DISTRO = FEDORA ]; then
         /usr/lib64/nvidia-current/bin/nvidia-installer -s --uninstall
     fi
 
-fi
-
-#	Make sure the card is enabled
-#
-if [ -x /usr/local/bin/bumblebee-enablecard ]; then
-  /usr/local/bin/bumblebee-enablecard
 fi
 
 #Unload the nvidia module
