More fixes to the bumblebee-configuration script...

diff --git a/install-files/ubuntu/bumblebee-disablecard.template b/install-files/ubuntu/bumblebee-disablecard.template
--- a/install-files/ubuntu/bumblebee-disablecard.template
+++ b/install-files/ubuntu/bumblebee-disablecard.template
@@ -6,29 +6,29 @@
 # Please note that the acpi_call module is need for these operations:
 # http://linux-hybrid-graphics.blogspot.com/2010/07/using-acpicall-module-to-switch-onoff.html
 
-rmmod nvidia
-if lsmod | grep -q nvidia; then
- echo "Error: could not unload nvidia module, leaving card turned on"
- exit
-fi
+#rmmod nvidia
+#if lsmod | grep -q nvidia; then
+# echo "Error: could not unload nvidia module, leaving card turned on"
+# exit
+#fi
 
-modprobe acpi_call
-if ! lsmod | grep -q acpi_call; then
-    echo "Error: acpi_call module not loaded"
-    exit
-fi
+#modprobe acpi_call
+#if ! lsmod | grep -q acpi_call; then
+#    echo "Error: acpi_call module not loaded"
+#    exit
+#fi
 
-acpi_call () {
-    echo "$*" > /proc/acpi/call
-    result=$(cat /proc/acpi/call)
-    case "$result" in
-     Error*)
-      echo "Disabling nVidia card failed ($result)."
-      ;;
-     *)
-      echo "Disabling nVidia card succeeded."
-     ;;
-    esac
-}
+#acpi_call () {
+#    echo "$*" > /proc/acpi/call
+#    result=$(cat /proc/acpi/call)
+#    case "$result" in
+#     Error*)
+#      echo "Disabling nVidia card failed ($result)."
+#      ;;
+#     *)
+#      echo "Disabling nVidia card succeeded."
+#     ;;
+#    esac
+#}
 
-INSERTPOWEROFF
+#INSERTPOWEROFF
